### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Magador** [Magador/eSmart#1]
# ToDo List
- [x] Factories
  - [x] Implement factories
  - [x] Validate implementation (see #2)
- [x] HTTP Requests (`HTTPClient`)
  - [x] `DocinfoService.getDoc()`
  - [x] `DocinfoService.getAttachment()`
  - [x] `DocinfoService.getSecondaryAttachments()`
  - [x] `GregService.getLDA()`
- [x] Implement `VehicleProjectServiceImpl` with `Element`
  - [x] `VehicleProjectServiceImpl.updateJfa()`
  - [x] `VehicleProjectServiceImpl.updateDameIqa()`
  - [x] `VehicleProjectServiceImpl.updateCommentNorm()`
- [ ] new `RuntimeException` for `ZipService` and `ChecksumService` ?
- [x] JUnit
  - [x] Docinfo (see #3)
  - [x] Greg
  - [x] ESmartFileRepository
  - [x] VehicleProjectServiceImpl
- [x] JAVADOC (see #5)
- [x] Logger (see #6 )
- [ ] Transfer Diagram Class into EA - SVN
