### ISSUE TITLE
Unit testing of domain.model.docinfo package

### ISSUE THREAD

**Issue by Magador** [Magador/eSmart#3]
### Implement the unit testing for the `domain.model.docinfo` package

The classes should be in `src/test/java` while the config should be in `src/test/resources`
#### Tasks
- [x] Write skeleton files
- [x] UT the `DocinfoDocFactory` interface (or implementation)
- [x] UT the `DocinfoService` interface (or implementation)
